### ISSUE TITLE
[Setup] Testing and CI/CD Configuration

### ISSUE THREAD

**Issue by CintiaSchutt** [CintiaSchutt/trackmyjob#12]
## Objective
Set up testing infrastructure and CI/CD pipelines for both web and mobile applications.

### Testing Setup
- [ ] Set up Jest and React Testing Library
- [ ] Configure test environment
- [ ] Add test utilities and helpers
- [ ] Create test templates

### CI/CD Pipeline
- [ ] Set up GitHub Actions workflow
- [ ] Configure Vercel deployment for web
- [ ] Set up EAS build for mobile
- [ ] Add environment secrets

### Test Coverage
- [ ] Add component tests
- [ ] Add integration tests
- [ ] Add API tests
- [ ] Set up coverage reporting

## GitHub Actions Workflow
```yaml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm test
      - run: npm run lint

  deploy-web:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  deploy-mobile:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: eas build --platform all --non-interactive
```

## Test Examples
```typescript
// Component Test Example
describe('JobCard', () => {
  it('renders job details correctly', () => {
    const job = {
      title: 'Software Engineer',
      company: 'Tech Corp',
      location: 'Remote'
    };
    
    render(<JobCard job={job} />);
    
    expect(screen.getByText('Software Engineer')).toBeInTheDocument();
    expect(screen.getByText('Tech Corp')).toBeInTheDocument();
    expect(screen.getByText('Remote')).toBeInTheDocument();
  });
});

// API Test Example
describe('Job Applications API', () => {
  it('creates a new application', async () => {
    const application = {
      company: 'Tech Corp',
      position: 'Senior Developer'
    };
    
    const { data, error } = await jobApplications.create(application);
    
    expect(error).toBeNull();
    expect(data).toMatchObject(application);
  });
});
```

## Definition of Done
- Test suite running successfully
- CI/CD pipeline working
- Web deployment automated
- Mobile builds configured
- Test coverage report working
- All secrets configured
- Documentation updated
